DROP TABLE IF EXISTS message_recipients;
DROP TABLE IF EXISTS messages;
DROP TABLE IF EXISTS ducks;
DROP TABLE IF EXISTS persons;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS users;

-- 1. TABLES CREATION --
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    email VARCHAR(255)
);

CREATE TABLE ducks (
    user_id BIGINT PRIMARY KEY,
    duck_type VARCHAR(50),
    speed DOUBLE PRECISION,
    stamina DOUBLE PRECISION,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE persons (
    user_id BIGINT PRIMARY KEY,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    occupation VARCHAR(255),
    empathy_level INT,
    birth_date DATE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    receiver_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED')),
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (receiver_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT unique_friendship UNIQUE (sender_id, receiver_id),
    CONSTRAINT check_distinct_users CHECK (sender_id <> receiver_id)
);

CREATE TABLE messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    sent_at TIMESTAMP,
    reply_to_id BIGINT,
    FOREIGN KEY (sender_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (reply_to_id) REFERENCES messages(id) ON DELETE SET NULL
);

CREATE TABLE message_recipients (
    message_id BIGINT NOT NULL,
    recipient_id BIGINT NOT NULL,
    PRIMARY KEY (message_id, recipient_id),
    FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE CASCADE,
    FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 2. USERS POPULATION --
INSERT INTO users (username, password, email) VALUES
('AquaDuck_01', 'dpass1', 'aqua1@h2.com'), -- ID 1
('AquaDuck_02', 'dpass2', 'aqua2@h2.com'), -- ID 2
('AquaDuck_03', 'dpass3', 'aqua3@h2.com'), -- ID 3
('AirDuck_04', 'dpass4', 'air4@h2.com'),   -- ID 4
('AirDuck_05', 'dpass5', 'air5@h2.com'),   -- ID 5
('John_2001', 'ppass1', 'john@h2.com'),    -- ID 6
('Jane_2002', 'ppass2', 'jane@h2.com'),    -- ID 7
('Mark_2003', 'ppass3', 'mark@h2.com'),    -- ID 8
('Eliza_2004', 'ppass4', 'eliza@h2.com'),  -- ID 9
('Gary_2005', 'ppass5', 'gary@h2.com');    -- ID 10

INSERT INTO ducks (user_id, duck_type, speed, stamina) VALUES
(1, 'SWIMMER', 3.5, 9.1),
(2, 'SWIMMER', 2.8, 8.5),
(3, 'SWIMMER', 4.0, 7.0),
(4, 'FLYING', 8.2, 5.5),
(5, 'FLYING', 9.5, 6.0);

INSERT INTO persons (user_id, first_name, last_name, occupation, empathy_level, birth_date) VALUES
(6, 'John', 'Smith', 'Engineer', 7, '1990-01-15'),
(7, 'Jane', 'Doe', 'Designer', 9, '1995-05-20'),
(8, 'Mark', 'Wilson', 'Manager', 5, '1985-11-01'),
(9, 'Eliza', 'Clark', 'Student', 8, '2000-03-10'),
(10, 'Gary', 'King', 'Pilot', 6, '1978-08-25');

-- 3. FRIENDSHIPS POPULATION  --
INSERT INTO friendships (sender_id, receiver_id, status) VALUES
(1, 2, 'APPROVED'),
(6, 1, 'APPROVED'),
(2, 3, 'APPROVED'),
(3, 4, 'APPROVED'),
(4, 5, 'APPROVED'),
(6, 7, 'APPROVED'),
(7, 8, 'APPROVED'),
(8, 9, 'APPROVED'),
(9, 10, 'APPROVED'),
(2, 7, 'APPROVED'),
(5, 10, 'APPROVED'),
(1, 10, 'APPROVED');

-- 4. MESSAGES POPULATION --

-- CONVERSATION 1: John (6) and Jane (7) --
INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (6, 'Hello Jane, are we meeting for coffee?', '2023-10-01 09:00:00', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (1, 7);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (7, 'Hi John! Yes, at 10 AM.', '2023-10-01 09:05:00', 1);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (2, 6);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (7, 'I might be 5 minutes late though.', '2023-10-01 09:05:30', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (3, 6);


-- CONVERSATION 2: AquaDuck (1) and John (6) --
INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (1, 'Quack! Do you humans have any bread?', '2023-10-01 12:00:00', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (4, 6);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (6, 'I have a sandwich.', '2023-10-01 12:02:00', 4);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (5, 1);


-- CONVERSATION 3: AirDuck_04 (4) and AirDuck_05 (5)
INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (4, 'Lets fly south.', '2023-11-01 08:00:00', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (6, 5);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (5, 'It is raining today.', '2023-11-01 08:01:00', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (7, 4);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (4, 'Rain is fine.', '2023-11-01 08:02:00', NULL);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (8, 5);

INSERT INTO messages (sender_id, content, sent_at, reply_to_id)
VALUES (5, 'Okay, regarding South, lets go tomorrow.', '2023-11-01 08:10:00', 6);
INSERT INTO message_recipients (message_id, recipient_id) VALUES (9, 4);